"""Functions for parsing TCX and GPX files into Pandas DataFrames."""

from collections.abc import Iterator
from os import PathLike
from typing import Any

from lxml import etree
import pandas as pd


def extract_xml_fields(element: Any) -> Iterator[tuple[str, Any]]:
    """Yields (name, value) pairs recursively through an XML element."""

    for el in element.iter():
        # Some (name, value) pairs are stored as XML attributes
        for key, value in el.attrib.items():
            localname = etree.QName(key).localname
            if localname != 'type':
                yield localname, value

        # In a TCX file, some values are buried in a 'Value' element
        if el.text is None or el.text.isspace():
            try:
                child = next(el.iterchildren())
                parent_localname = etree.QName(el).localname
                child_localname = etree.QName(child).localname
                if child_localname == 'Value':
                    yield parent_localname, child.text
            except StopIteration:
                pass

        # But most values are recorded as leaf element text
        else:
            localname = etree.QName(el).localname
            if localname != 'Value':
                yield localname, el.text


def cleanup_xml_dataframe(df: pd.DataFrame, time_col: str) -> pd.DataFrame:
    """Common post-processing for DataFrames extracted from XML elements."""

    df = df.convert_dtypes().astype(float, errors='ignore')
    df[time_col] = pd.to_datetime(df[time_col])

    # Conversion from meters and m/s to km and kph is done to align with
    # processing done by fitdecode.StandardUnitsDataProcessor. Note these column
    # names apply to TCX files only; GPX files don't seem to have distance and
    # speed information.
    for col in df.columns:
        if 'Distance' in col:
            df[col] = df[col] / 1000.0
            df = df.rename(columns={col: col.replace('Meters', 'Km')})
        if 'Speed' in col:
            df[col] = df[col] * 60.0 * 60.0 / 1000.0

    return df


def parse_tcx(
    file: str | PathLike[str] | Any,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    """Loads a TCX activity into Pandas DataFrames.

    Assumes that the TCX file is all one activity. Files with multiple
    activities will be merged into one set of return values, possibly
    over-writing some fields.

    Args:
        file: File-like or path-like object. A path-like argument ending in
            '.gz' will be transparently unzipped before processing.

    Returns:
        Tuple containing records, laps, and additional metadata.
    """

    # lxml takes care of identifying and handling a gzipped file
    parser = etree.XMLParser(recover=True)
    root = etree.parse(file, parser).getroot()

    # TCX files occasionally have duplicate timestamps, just drop those
    records = pd.DataFrame(
        dict(extract_xml_fields(element))
        for element in root.iter('{*}Trackpoint')
    )
    records = cleanup_xml_dataframe(records, 'Time').set_index('Time')
    records = records[~records.index.duplicated()]

    for element in root.iter('{*}Track'):
        element.getparent().remove(element)

    laps = pd.DataFrame(
        dict(extract_xml_fields(element))
        for element in root.iter('{*}Lap')
    )
    laps = cleanup_xml_dataframe(laps, 'StartTime')

    for element in root.iter('{*}Lap'):
        element.getparent().remove(element)

    extra = dict(extract_xml_fields(root))
    extra.pop('schemaLocation', None)

    return records, laps, extra


def parse_gpx(
    file: str | PathLike[str] | Any,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    """Loads a GPX activity into a Pandas DataFrame.

    Assumes that the GPX file is all one activity. Files with multiple tracks
    will be merged into one set of return values, possibly over-writing some
    fields. Waypoints and routes in the GPX file are ignored.

    Args:
        file: File-like or path-like object. A path-like argument ending in
            '.gz' will be transparently unzipped before processing.

    Returns:
        Tuple containing records, laps, and additional metadata. Note GPX files
        don't have lap information, so the laps DataFrame will be empty.
    """

    # Note there is a 'gpxpy' library that provides comprehensive handling of
    # GPX files. For GPX files generated by Strava and Garmin Connect it works
    # well enough to suck the data straight out of the XML like we do above for
    # TCX files.

    parser = etree.XMLParser(recover=True)
    root = etree.parse(file, parser).getroot()

    records = pd.DataFrame(
        dict(extract_xml_fields(element))
        for element in root.iter('{*}trkpt')
    )
    records = cleanup_xml_dataframe(records, 'time').set_index('time')
    records = records[~records.index.duplicated()]

    for element in root.iter('{*}trkseg', '{*}rte', '{*}wpt'):
        element.getparent().remove(element)

    extra = dict(extract_xml_fields(root))
    extra.pop('schemaLocation', None)

    return records, pd.DataFrame(), extra
