"""Default column lists returned by ``ActivityParser``, shared across FIT/TCX/GPX."""

DEFAULT_RECORD_COLUMNS: tuple[str, ...] = (
    "latitude",
    "longitude",
    "altitude",
    "distance",
    "speed",
    "cadence",
    "heart_rate",
    "power",
    "left_balance",
    "right_balance",
    "accumulated_power",
    "temperature",
    "water_temperature",
    "depth",
    "course",
    "bearing",
)

DEFAULT_LAP_COLUMNS: tuple[str, ...] = (
    "start_time",
    "total_elapsed_time",
    "total_timer_time",
    "start_position_lat",
    "start_position_long",
    "end_position_lat",
    "end_position_long",
    "total_distance",
    "total_ascent",
    "total_descent",
    "avg_vam",
    "avg_speed",
    "max_speed",
    "avg_cadence",
    "max_cadence",
    "total_strokes",
    "steps",
    "avg_heart_rate",
    "max_heart_rate",
    "time_in_hr_zone",
    "avg_power",
    "max_power",
    "normalized_power",
    "left_balance",
    "right_balance",
    "time_in_power_zone",
    "total_work",
    "avg_temperature",
    "max_temperature",
    "total_calories",
    "total_fat_calories",
)
