"""Maps TCX and GPX sport vocabulary onto the FIT profile's."""

from functools import cache

from garmin_fit_sdk import Profile

# TrainingCenterDatabasev2.xsd constrains Sport_t to exactly these three values.
_TCX_SPORTS = {"Running": "running", "Biking": "cycling", "Other": "generic"}

# GPX <trk><type> is free text, and GPX files generated by Strava use Strava's sport
# vocabulary. Strava sports that do not cleanly map to a FIT sport (e.g., Handcycle) are
# left out deliberately, passing through unchanged.
_STRAVA_SPORTS = {
    "Ride": "cycling",
    "VirtualRide": "cycling",
    "MountainBikeRide": "cycling",
    "GravelRide": "cycling",
    "EBikeRide": "e_biking",
    "Run": "running",
    "VirtualRun": "running",
    "TrailRun": "running",
    "Walk": "walking",
    "Hike": "hiking",
    "Swim": "swimming",
    "AlpineSki": "alpine_skiing",
    "NordicSki": "cross_country_skiing",
    "Snowboard": "snowboarding",
    "Snowshoe": "snowshoeing",
    "IceSkate": "ice_skating",
    "InlineSkate": "inline_skating",
    "StandUpPaddling": "stand_up_paddleboarding",
    "Kitesurf": "kitesurfing",
    "Windsurf": "windsurfing",
    "RockClimbing": "rock_climbing",
}


@cache
def _fit_sports() -> frozenset[str]:
    """Every sport value in the installed FIT profile."""
    return frozenset(Profile["types"]["sport"].values())


def normalize_sport(value: str | None) -> str | None:
    """Maps a TCX/GPX sport onto the FIT sport vocabulary, or passes it through."""
    if value is None:
        return None

    alias = _TCX_SPORTS.get(value) or _STRAVA_SPORTS.get(value)
    if alias is not None:
        return alias

    lowered = value.lower()
    return lowered if lowered in _fit_sports() else value
